### ISSUE TITLE
map did not show in my app 

### ISSUE THREAD

**Issue by aliaaosama** [amyogiji/ionic3-Geolocation-GoogleMap-Native-Geocoder#1]
i tried all steps as written in this app but map is not loading when using geolocation plugin

**Comment by amyogiji** [comment]
You need to share the error you see or a repo

**Comment by hanifmazlan** [comment]
i got this error

`Error: exec proxy not found for :: NativeGeocoder :: reverseGeocode`
>ERROR Error: Uncaught (in promise): Missing Command Error
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4620)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at <anonymous>

**Comment by hanifmazlan** [comment]
Code working. must running in cordova device. cannot in cordova browser. Thanx

**Comment by amyogiji** [comment]
when you use any cordova plugin always test it on device. as this issue is resolved i am closing
