### ISSUE TITLE
map not showing

### ISSUE THREAD

**Issue by mchellchristy** [amyogiji/ionic3-Geolocation-GoogleMap-Native-Geocoder#2]
Thanks for the code, but why map not showing in android?

**Comment by amyogiji** [comment]
I can't tell this way
can you tell what errors you have?

**Comment by amyogiji** [comment]
Can you please share some code here.

**Comment by mchellchristy** [comment]
i'm just follow the code but when i build android and open the apk, the maps not display. Just the information reverse geocode

**Comment by mchellchristy** [comment]
the code same with this github

**Comment by 7thZone** [comment]
plz check your config.xml it has the existing google map api key. please create your own api key
also go to `chrome://inspect/#devices ` in your chrome and check the console for any error.
